name: Lerna CI
on: [push, pull_request]
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn global add lerna
    - run: lerna bootstrap
    - run: yarn test-ci
